server:
  port: 6062
spring:
  application:
    name: gateway-filter-factories
  profiles:
    include: prefixpath
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
