#id:唯一标识
#uri:跳转地址
#Before:匹配[2022-01-23T17:42:47.789-07:00[America/Denver]]这个时间之前所有的请求到{uri}
#localhost:6061/** -> http://www.cnblogs.com/**
#eg:localhost:6061/leizzige -> http://www.cnblogs.com/leizzige

spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://www.cnblogs.com
          predicates:
            - Before=2022-01-23T17:42:47.789-07:00[America/Denver]